language: php

php:
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
    - .phpunit

env:
  matrix: SYMFONY_VERSION=3.4.*
  global: SYMFONY_PHPUNIT_DIR=.phpunit SYMFONY_PHPUNIT_VERSION=5.7

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION=4.0.* DEPS=dev
    - php: 5.6
      env: SYMFONY_VERSION=2.8.* COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: SYMFONY_VERSION=3.2.*
    - php: 7.2
      env: SYMFONY_VERSION=3.3.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
  fast_finish: true

before_install:
  - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - if [ "$DEPS" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi

install: composer update --prefer-dist $COMPOSER_FLAGS

script: vendor/bin/simple-phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
